buildscript {
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.7.3"
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        mavenLocal() // InVxTermux: com.invapp:termux-shared/terminal-view published from involvex/termux-app
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
